# The URL the site will be built for
base_url = "https://sebcossu.github.io/blog/"

# Core metadata
title = "Night Cup"
description = "Nightly notes on coding and computers..."

# Features
compile_sass = false
build_search_index = true
generate_feed = true
generate_sitemap = true

# Tags/Categories
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

